services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=marjane'
      - 'POSTGRES_PASSWORD=Youcode@2023'
      - 'POSTGRES_USER=postgres'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
        - marjane
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - marjane
networks:
  marjane:
      name: marjane
      driver: bridge
volumes:
  postgres-db:
    driver: local